version: "3.8"

services:
  chatgpt-bot:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis
  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:latest
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
