version: "3.9"

services:
  chatgpt-bot:
    image: ponimon4ik/telegram_gpt:latest
#    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: bot_redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
